language: python
python:
  - "2.7"
install: 
    - pip install pybuilder
    - pip install gitpython
    - pip install coveralls
    - pyb install_dependencies
script: pyb -X verify analyze

after_success:
  - coveralls
